# Notice the v1beta3 version
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: teste-action
  title: Test Action template
  description: scaffolder v1beta12 template demo
spec:
  owner: backstage/techdocs-core
  type: service

#   these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Write your parent path
      required:
        - name
        - environmentSize
      properties:
        name:
          title: Name
          type: string
          description: 'parent path'
          ui:autofocus: true
          ui:options:
            rows: 5
        environmentSize:
          title: Environment Size
          type: string
          description: 'Environment Size'
          ui:autofocus: true
          ui:options:
            rows: 5
#         owner:
#           title: Owner
#           type: string
#           description: Owner of the component
#           ui:field: OwnerPicker
#           ui:options:
#             allowedKinds:
#               - Group
#     - title: Choose a location
#       required:
#         - repoUrl
#       properties:
#         repoUrl:
#           title: Repository Location
#           type: string
#           ui:field: RepoUrlPicker
#           ui:options:
#             allowedHosts:
#               - github.com

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: create-compose
      name: Create Compose
      action: create-compose-env
      input:
        parent: '{{ parameters.name }}'
        environment:
          config:
            environmentSize: '{{ parameters.environmentSize }}'
#       input:
#         values:
#           parent: '{{ parameters.name }}'
      #   values:
      #     name: ${{ parameters.name }}
      #     owner: ${{ parameters.owner }}

  output:
    parent: ${{ steps.create-compose.output.parent }}
    
